visitors_backend_details:
    resource: "@BugBusterVisitorsBundle/Controller"
    type: attribute

visitors_frontend_screencount:
    resource: "@BugBusterVisitorsBundle/Controller"
    type: attribute

visitors_frontend_countervalues:
    resource: "@BugBusterVisitorsBundle/Controller"
    type: attribute
