services:
    _defaults: { autowire: true, autoconfigure: true, public: false }

    # bug_buster_visitors.logger:
    #     class: "BugBuster\\VisitorsBundle\\Classes\\VisitorLogger"
    BugBuster\VisitorsBundle\Classes\VisitorLogger:
        public: true
        arguments: 
            - '@service_container'
            - '@logger'
            - '@monolog.logger.contao'
        tags:
            - 
                name: monolog.logger
                channel: visitors

    bug_buster_visitors.logger:
        alias: BugBuster\VisitorsBundle\Classes\VisitorLogger
        public: true

    # entspricht monolog.formatter.line
    # monolog.formatter.visitors:
    #     class: Monolog\Formatter\LineFormatter
    #     arguments:
    #         - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
