services:
    _defaults: { autowire: true, autoconfigure: true, public: true }

    BugBuster\VisitorsBundle\Controller\FrontendModule\VisitorsFrontendController:
        public: true
        tags:
            -
                name: contao.frontend_module
                category: miscellaneous
                type: visitors
                template: mod_visitors_fe_all
                renderer: esi
            -
                name: container.service_subscriber

        
